### ISSUE TITLE
[REQ] Add ZeroTier to the Beginners Guide

### ISSUE THREAD

**Issue by d-Rickyy-b** [justSem/r-selfhosted-security#3]
**Please state which guide your request refers to.**
https://github.com/justSem/r-selfhosted-security/tree/main/beginners-guide

**Describe the solution you'd like**
I think it would be cool to add ZeroTier to the Beginners Guide (& later maybe HowTo's). ZeroTier offers VPN functionality (and a lot more) and allows to build a network of connected devices, as if they were connected to a single switch with additional firewalling capabilities. It's very popular within some gaming communities, especially for "remote LAN parties". But it's also suitable for connecting devices to your home lab for example.

Resources:
- https://www.zerotier.com/
- https://blog.rico-j.de/zerotier-one/

Full disclosure: The last link is a link to my own blog. I tried to write a good article for everyone that never heard about ZeroTier before.

**Comment by justsem** [comment]
Let me start off by saying that I know ZeroTier, but wether to add it or not depends on your view.

The question that comes to my mind is wether using services like ZeroTier, Cloudflare, etc. defeat the idea of self-hosting. (Because you'd be relying on 3rd party networks/services while that's exactly what you'd not want when self-hosting)

So I'm not declining your request :) I'm simply asking: "What's your view on this?"

**Comment by d-Rickyy-b** [comment]
> The question that comes to my mind is wether using services like ZeroTier, Cloudflare, etc. defeat the idea of self-hosting. (Because you'd be relying on 3rd party networks/services while that's exactly what you'd not want when self-hosting)

On the one hand, ZeroTier's philosophy is all about [decentralization](https://adamierymenko.com/decentralization.html). But I get your point that ZeroTier is partly centralized: When creating the p2p connection, you need to contact ZeroTier's root server once.

But ZeroTier even offers you to the ability to [create your own root servers, called "moons"](https://docs.zerotier.com/zerotier/moons/). So I think that you are not that dependent as it might seem at first glance.
My intention in adding it would simply be to give an alternative to hosting your own, publicly reachable VPN gateway.

> So I'm not declining your request :) I'm simply asking: "What's your view on this?"

Even if you dislike the idea of adding it, that'd be totally fine :) I just thought another alternative to reach your self hosted stuff might be helpful for a few people.

**Comment by justsem** [comment]
Hmm, I wasn't aware of those moons. Admittedly it has been a while since I used zerotier (read: 2019).

So yes, given those facts I'd be a welcome addition! :) feel free to make a PR, if not I'll edit it in this week.

**Comment by justsem** [comment]
It has taken me longer then expected. (CERT Life is a unpredictable thing ;) ) but I've edited it in for you and referred to your article.
